### ISSUE TITLE
Feature request: expose functionality as API

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/foundryvtt-cli#10]
Use case: I already have a significant chunk of idiosyncratic build tooling written for Foundry modules, and would really only benefit from being able to use a few features in this CLI. As such, I would love it if could install this, or another library, package, and be able to do e.g.

```js
import package from "foundry-lib"

package.unpack("./compendiums/my-db-file.db")

// do stuff

package.pack("./compendiums/my-db-file.db")
```

**Comment by JPMeehan** [comment]
Echoing support for this.

**Comment by aMediocreDad** [comment]
Use my fork for now: https://github.com/aMediocreDad/foundryvtt-cli
