### ISSUE TITLE
fvtt configure view does not work as advertised

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt-cli#11]
The readme suggests that `fvtt configure view` can be used to "View your current configuration", but "view" is not recognized as a valid sub-action of `fvtt configure`

![image](https://user-images.githubusercontent.com/2468703/235309176-d4b3cc03-3eb2-48f6-937d-97f1d73bec8a.png)

**Comment by cswendrowski** [comment]
Closed as of v0.0.8
