### ISSUE TITLE
Attempting to unpack a V10 NEDB database fails because it is looking for a V11 LevelDB lockfile

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt-cli#12]
The `isFileLocked` function is called regardless of whether the `dbMode` is `"nedb"` or `"classic-level"` but this lock file will only exist if the dbMode is classic-level. This prevents pack/unpack operations from being possible in a pure v10 environment.

**Comment by cswendrowski** [comment]
Closed as of v0.0.8
