### ISSUE TITLE
Erroneously output to working directory when the --outputDirectory flag is set to a subdirectory using a relative filepath

### ISSUE THREAD

**Issue by anthonyronda** [foundryvtt/foundryvtt-cli#16]
The bug title is just a guess as to the cause of the behavior

Reproduction steps
With the cli fully configured
0. `cd (userdata location)/Data/modules/1001-fish`
1. `fvtt package workon "1001-fish" --type "Module"`
2. `fvtt package unpack fish --inputDirectory "./packs" --outputDirectory "./packs/newFolder"`

Expected behavior: jsons are written to 1001-fish/packs/newFolder/ 
(newFolder is created if not already present)

Actual behavior: jsons are written to 1001-fish/
(newFolder is created if not already present)

**Comment by Fyorl** [comment]
This should be fixed in the latest release now.
