### ISSUE TITLE
Error: Assignment to constant variable

### ISSUE THREAD

**Issue by anthonyronda** [foundryvtt/foundryvtt-cli#18]
<img width="419" alt="image" src="https://github.com/foundryvtt/foundryvtt-cli/assets/1410433/c3a5a423-30c4-4d3d-b905-8f91455ceb60">

https://github.com/foundryvtt/foundryvtt-cli/blob/db6946054beae2770c12298035365b56cd98357e/commands/package.mjs#L303

In 0.0.8, as a workaround, you must set your own output and input directories

**Comment by MrVauxs** [comment]
Hi, has this been released yet?
I cant use the cli because of it. The latest version is still 0.0.8
