### ISSUE TITLE
dataPath is used two different ways

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt-cli#6]
`fvtt launch` directly pulls the `datapath` variable, when it should be launching the parent folder. Rather than change the level the datapath is set, it should instead change `--dataPath=${dataPath}` to `--dataPath=./${dataPath}` or something along those lines to grab the parent folder.

**Comment by aaclayton** [comment]
Agree this is an issue. The "Data Path" should be the parent folder that contains `Config`, `Logs`, `Data`, etc... the same as the `--dataPath` argument that would be passed to Foundry VTT itself. The CLI is incorrectly expecting the `Data` subfolder to be defined as the "dataPath"

**Comment by cswendrowski** [comment]
Closed as of v0.0.8
