### ISSUE TITLE
Unpack crashes if forward slash is used in an item name

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt-cli#7]
The unpackage command does not sanitize the name of an item if there's a forward slash, leading to errors like `Error: ENOENT: no such file or directory, open '.../Local/FoundryVTT/Data/systems/a5e/packs/rareSpells/_source/fiendish_antipathy/sympathy_zg9p7w7f6sqzmyvk.json'` (ellipsis in path name added by me).

This occurs when unpacking both leveldb as well as nedb files.

**Comment by toastygm** [comment]
I'm having the same issue.

**Comment by cswendrowski** [comment]
Closed as of v0.0.8
