### ISSUE TITLE
Request: Convert nedb to ldb

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt-cli#9]
As a developer, it would be helpful if I could unpack an nedb file and pack it into a LevelDB file using the CLI. Right now the lack of a _key value in the unpacked files prevents this flow from working.

Additionally/alternatively, a form of key generation would be useful for directly creating a JSON/YAML file in my _source folder and then having it packed back into the LevelDB

**Comment by cswendrowski** [comment]
It won't be possible to generate a key from a fresh manually created JSON, as we lack the details on what the document type is, but the next version will ship with nedb writing a `_key`

**Comment by cswendrowski** [comment]
Closed as of v0.0.8
